version: '3.8'

services:
  db:
    image: postgres:15
    container_name: sql-db
    working_dir: /data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: employees
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      # Maps your local dataset folder to the auto-init directory
      - ./hr-schema/postgres/dataset:/docker-entrypoint-initdb.d
    networks:
      - sql-sandbox-net 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d employees"]
      interval: 5s
      timeout: 5s
      retries: 5

  gui:
    image: dpage/pgadmin4
    container_name: sql-gui
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - sql-sandbox-net
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg-data:
networks:
  sql-sandbox-net:
    name: sql-sandbox-net
